name: Build CV PDF

on:
  push:
    paths:
      - "_data/cv.yaml" 
      - ".github/workflows/cv-pdf.yml"
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # 使用最新的 Python 3 版本

      - name: Install rendercv
        run: pip install rendercv[full]

      - name: Generate PDF
        run: rendercv render _data/cv.yaml

      - name: Move PDF to files folder
        run: mv rendercv_output/Chunlei_Li_CV.pdf files/cv.pdf

      - name: Move Markdown to files folder
        run: mv rendercv_output/Chunlei_Li_CV.md files/cv.md

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: CV-PDF
          path: files/cv.pdf

      - name: check
        run: |
          ls files
          ls _data/rendercv_output

      # ---------- 新增：提交 PDF 到 pdf 分支 ----------
      - name: Commit
        run: |
          git config --global user.name 'cl li (github-actions[bot])'
          git config --global user.email 'li_cl@foxmail.com'
          git commit -am "Automate CV PDF update"
          git push origin pdf