name: Build CV PDF

on:
  push:
    paths:
      - "_data/cv.json"
      - ".github/workflows/cv.yml"
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install resume-cli
        run: npm install -g resume-cli

      - name: Generate PDF
        run: resume export files/cv.pdf --theme paper

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: CV-PDF
          path: files/cv.pdf
